### PR TITLE
feat: improve parsing for a frame-rate attribute

### PR DESCRIPTION
**Pull request by gjanblaszczyk**
The 'FRAME-RATE' attribute should be a floating-point number type rather than a string.

### CODE REVIEW

**Comment by gjanblaszczyk** [comment]
The PR is related to this https://github.com/videojs/mpd-parser/pull/159

**Comment by gesinger** [comment]
This looks good @gjanblaszczyk , thank you. The only concern I have is that it technically breaks the old output. Although it should be minor, and is more appropriate as a number, we should consider a small major for this.

**Comment by gjanblaszczyk** [comment]
Thanks for the feedback @gesinger. @gkatsev any thoughts?

**Comment by gkatsev** [comment]
Yeah, technically a breaking change. Don't see a problem with making a major version of m3u8-parser, though.

**Review by gkatsev — APPROVED** [review]
Just needs a `BREAKING CHANGE:` in the footer when we merge.

**Review by gesinger — APPROVED** [review]

**Comment by gjanblaszczyk** [comment]
@gkatsev Is it enough to add this footer message during GitHub squash and merge action? or maybe I should do something more...

**Comment by gkatsev** [comment]
yup, that would do it. I rarely if ever merge locally anymore and we prefer squash+merge in the video.js projects.

**Pull request merged**
