### PR TITLE
Linter update

### PR DESCRIPTION
**Pull request by pswolfe**
## Description

 Updated ```videojs-standard``` to the latest version and applied linter changes across the codebase.

## Specific Changes proposed

When attempting to run tests, the linter was found to be breaking due to an out-of-date ```videojs-standard``` package version. The version has been updated from ```4.0.2``` to ```5.2.0``` and all recommended linter changes have been applied across the codebase (mostly const vs let changes).

### CODE REVIEW

**Comment by pswolfe** [comment]
According to Travis, the ```videojs-standard``` library is failing when accessed via node 0.12 and 0.10. Doesn't seem to register arrow notation for functions.

**Comment by gkatsev** [comment]
Ah, can you update the travis.yml to remove `0.12` and `0.10` from the nodejs list?

**Comment by nickygerritsen** [comment]
Is it an idea to add a test with two program date times to check it keeps the first one?

Otherwise LGTM

**Comment by pswolfe** [comment]
@nickygerritsen Modified the existing program date time manifest test. Ran the test and it passed; should be good to go.

**Comment by dmlap** [comment]
In general, the last value "wins" for other properties in the m3u8 parser. Are there special considerations around date-time that would make that a bad decision?

**Comment by pswolfe** [comment]
The rationale for only reading the first value is to make time tracking consistent for the duration of a user's viewing of the stream / VOD. True, a ```#EXT-X-PROGRAM-DATE-TIME``` can be changed via a discontinuity, but this will throw off the live time as far as the user is concerned. That being said, [this is what the HLS spec says about playback and ```#EXT-X-PROGRAM-DATE-TIME```](https://tools.ietf.org/html/draft-pantos-http-live-streaming-19#section-6.3.3):

> 
If the first EXT-X-PROGRAM-DATE-TIME tag in a Playlist appears after
   one or more media segment URIs, the client SHOULD extrapolate
   backward from that tag (using EXTINF durations and/or media
   timestamps) to associate dates with those segments.  To associate a
   date with any other media segment that does not have an EXT-X
   -PROGRAM-DATE-TIME tag applied to it directly , the client SHOULD
   extrapolate forward from the last EXT-X-PROGRAM-DATE-TIME tag
   appearing before that segment in the Playlist.

By the standard, we should restart the time tracking anytime a new ```#EXT-X-PROGRAM-DATE-TIME``` is parsed. This would lead to an inconsistent timing, but would follow the standard. Thoughts?

**Comment by dmlap** [comment]
It's definitely weird but I'd be inclined to follow the spec. Anyone else have an opinion?

**Comment by BrandonOCasey** [comment]
following the spec seems like the logical thing to do

**Comment by pswolfe** [comment]
I reverted my changes to read only the first the program date time tag so that we remain compliant with the spec. The changes that remain fix the tests (which were broken because of the out-of-date linter) and bring the linting up to the current standard.

**Comment by dmlap** [comment]
Thanks for updating the linter! LGTM

**Comment by pswolfe** [comment]
Cool, feel free to merge this at your leisure then. Thanks!

**Comment by BrandonOCasey** [comment]
LGTM!

Sorry for taking so long to merge this! and thanks again for the PR!

**Comment by BrandonOCasey** [comment]
does this PR only contain linter updates at this point?

**Pull request merged**
